{% set name = "daggerpy" %}
{% set version = "0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daggerpy-{{ version }}.tar.gz
  sha256: b23dc3ec9f7b4f986ffbe875b7ec3e1c150fa314639a3cba9145ed4d5418c2a3

build:
  skip: true  # [py2k]
  entry_points:
    - dagger=dagger.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pybind11
    - pip
  run:
    - python
    - click >=7.0
    - pybind11

test:
  imports:
    - dagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bgailleton/DAGGER
  summary: DAG tools to process numerical topography and landscape evolution models
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgailleton
