{% set name = "daggerpy" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/daggerpy-{{ version }}.tar.gz
  sha256: c432594bd0aa3f3287ee43c006715c7f08e7910e5dfcf023c4de58af07d7f29b

build:
  skip: true  # [py2k]
  entry_points:
    - dagger=dagger.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - pybind11
    - numpy <=1.50
    - xtensor
    - xtensor-python
    - pip
  run:
    - python
    - click >=7.0
    - pybind11
    - numpy <=1.50
    - xtensor
    - xtensor-python

test:
  imports:
    - dagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bgailleton/DAGGER
  summary: DAG tools to process numerical topography and landscape evolution models
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgailleton
