{% set name = "daggerpy" %}
{% set version = "0.0.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/daggerpy-{{ version }}.tar.gz
  sha256: 9f13c17b5f482221697c668090435ce6ffe589ae54df9d130f88f0a642db3066

build:
  skip: true  # [py2k]
  entry_points:
    - dagger=dagger.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python
    - numpy >=2.0
    - pybind11
  host:
    - python
    - pybind11
    - numpy >=2.0
    - xtensor
    - xtensor-python
    - pip
  run:
    - python
    - click >=7.0
    - pybind11
    - numpy >=2.0

test:
  imports:
    - dagger
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bgailleton/DAGGER
  summary: DAG tools to process numerical topography and landscape evolution models
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgailleton
